# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/Gonçalo Cunha/Desktop/Tese/thesis"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/Gonçalo Cunha/Desktop/Tese/thesis"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/Gonçalo Cunha/Desktop/Tese/thesis/CMakeFiles" "/mnt/c/Users/Gonçalo Cunha/Desktop/Tese/thesis/CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/Gonçalo Cunha/Desktop/Tese/thesis/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

# target to build an object file
CalibrationRoutine.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CalibrationRoutine.o
.PHONY : CalibrationRoutine.o

# target to preprocess a source file
CalibrationRoutine.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CalibrationRoutine.i
.PHONY : CalibrationRoutine.i

# target to generate assembly for a file
CalibrationRoutine.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CalibrationRoutine.s
.PHONY : CalibrationRoutine.s

# target to build an object file
iCub/Robot.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/iCub/Robot.o
.PHONY : iCub/Robot.o

# target to preprocess a source file
iCub/Robot.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/iCub/Robot.i
.PHONY : iCub/Robot.i

# target to generate assembly for a file
iCub/Robot.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/iCub/Robot.s
.PHONY : iCub/Robot.s

# target to build an object file
iCubLimb/iCubLimb.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/iCubLimb/iCubLimb.o
.PHONY : iCubLimb/iCubLimb.o

# target to preprocess a source file
iCubLimb/iCubLimb.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/iCubLimb/iCubLimb.i
.PHONY : iCubLimb/iCubLimb.i

# target to generate assembly for a file
iCubLimb/iCubLimb.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/iCubLimb/iCubLimb.s
.PHONY : iCubLimb/iCubLimb.s

# target to build an object file
iCubVision/ArucoDetector.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/iCubVision/ArucoDetector.o
.PHONY : iCubVision/ArucoDetector.o

# target to preprocess a source file
iCubVision/ArucoDetector.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/iCubVision/ArucoDetector.i
.PHONY : iCubVision/ArucoDetector.i

# target to generate assembly for a file
iCubVision/ArucoDetector.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/iCubVision/ArucoDetector.s
.PHONY : iCubVision/ArucoDetector.s

# target to build an object file
iCubWorld/simobjloader.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/iCubWorld/simobjloader.o
.PHONY : iCubWorld/simobjloader.o

# target to preprocess a source file
iCubWorld/simobjloader.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/iCubWorld/simobjloader.i
.PHONY : iCubWorld/simobjloader.i

# target to generate assembly for a file
iCubWorld/simobjloader.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/iCubWorld/simobjloader.s
.PHONY : iCubWorld/simobjloader.s

# target to build an object file
main.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.o
.PHONY : main.o

# target to preprocess a source file
main.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.s
.PHONY : main.s

# target to build an object file
utils/utils.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/utils/utils.o
.PHONY : utils/utils.o

# target to preprocess a source file
utils/utils.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/utils/utils.i
.PHONY : utils/utils.i

# target to generate assembly for a file
utils/utils.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/utils/utils.s
.PHONY : utils/utils.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... CalibrationRoutine.o"
	@echo "... CalibrationRoutine.i"
	@echo "... CalibrationRoutine.s"
	@echo "... iCub/Robot.o"
	@echo "... iCub/Robot.i"
	@echo "... iCub/Robot.s"
	@echo "... iCubLimb/iCubLimb.o"
	@echo "... iCubLimb/iCubLimb.i"
	@echo "... iCubLimb/iCubLimb.s"
	@echo "... iCubVision/ArucoDetector.o"
	@echo "... iCubVision/ArucoDetector.i"
	@echo "... iCubVision/ArucoDetector.s"
	@echo "... iCubWorld/simobjloader.o"
	@echo "... iCubWorld/simobjloader.i"
	@echo "... iCubWorld/simobjloader.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... utils/utils.o"
	@echo "... utils/utils.i"
	@echo "... utils/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

